### ISSUE TITLE
Entire project foundation is flawed - please do not continue

### ISSUE THREAD

**Issue by tjtelan** [tan-ad/SignWave#1]
While I am not personally deaf/hearing-impaired, I am a member of the Deaf community (please note the distinction between deaf and Deaf). It is evident that none of the individuals involved in this project have experience interacting with this community, which is somewhat frustrating and disappointing.

I acknowledge that there is no malicious intent behind this project. However, it is another illustration of the tech community's tendency to be unaware and presumptuous, potentially leading others to develop tools without a solid foundation. Effective communication through sign language involves not just hand movements but also facial expressions and body positioning.

I believe that one can grasp the complexity of this issue by considering the limitations of text-to-text language translations, which often result in technically accurate but conceptually distorted outcomes. Directly translating words into signs without considering the underlying concepts can lead to a lack of meaning and intensity, particularly for those unfamiliar with sign language. It's akin to trying to port a PS5 game to a [Game and Watch](https://en.wikipedia.org/wiki/Game_%26_Watch) device. By relying solely on only hands in your approach, you're always losing essential contextual information from the words.

In my opinion, a tool like this will never be sufficiently functional for genuine communication with the intended audience without input from culturally Deaf, hard of hearing, or CODA (Children of Deaf Adults) developers. While it may serve as a valuable learning experience, it is crucial to acknowledge that without validation from the Deaf community, this project may remain little more than a resume booster.

I recommend updating your README to reflect this reality and considering starting afresh from a more inclusive design perspective. Simply writing more code will not address the fundamental issues at play. I encourage you to engage with the Deaf community and involve individuals with the necessary cultural and linguistic insights.

For additional insights on this topic, I suggest at least reading the following:
- "Sign Language Translators Are Cool, But Are They Useful?" (https://www.smithsonianmag.com/innovation/sign-language-translators-are-cool-but-are-they-useful-180971535/)
- "Nothing About Us Without Us" (https://en.wikipedia.org/wiki/Nothing_about_us_without_us)

I want to acknowledge that this is a technically impressive project. So please take this feedback and be proud of what you've got here.

**Comment by tan-ad** [comment]
Thank you for the thoughtful comment. The issue of sentence structure and grammar as well as the difference of the aforementioned between different sign languages were considered and addressed during our pitch for the hackathon this project was built for. I acknowledge that the word-for-word method we use for translation does not solve the problem effectively (Google took an ML approach to achieve their translation accuracy). This serves as no more than a technically interesting project.
